<?php

namespace Database\Seeders;

use App\Models\Bendera;
use Illuminate\Database\Seeder;

class BenderaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $benderas = [
            ['kode' => 'IDN', 'nama_negara' => 'Indonesia'],
            ['kode' => 'AFG', 'nama_negara' => 'Afghanistan'],
            ['kode' => 'ALB', 'nama_negara' => 'Albania'],
            ['kode' => 'DZA', 'nama_negara' => 'Algeria'],
            ['kode' => 'AND', 'nama_negara' => 'Andorra'],
            ['kode' => 'AGO', 'nama_negara' => 'Angola'],
            ['kode' => 'ATG', 'nama_negara' => 'Antigua and Barbuda'],
            ['kode' => 'ARG', 'nama_negara' => 'Argentina'],
            ['kode' => 'ARM', 'nama_negara' => 'Armenia'],
            ['kode' => 'AUS', 'nama_negara' => 'Australia'],
            ['kode' => 'AUT', 'nama_negara' => 'Austria'],
            ['kode' => 'AZE', 'nama_negara' => 'Azerbaijan'],
            ['kode' => 'BHS', 'nama_negara' => 'Bahamas'],
            ['kode' => 'BHR', 'nama_negara' => 'Bahrain'],
            ['kode' => 'BGD', 'nama_negara' => 'Bangladesh'],
            ['kode' => 'BRB', 'nama_negara' => 'Barbados'],
            ['kode' => 'BLR', 'nama_negara' => 'Belarus'],
            ['kode' => 'BEL', 'nama_negara' => 'Belgium'],
            ['kode' => 'BLZ', 'nama_negara' => 'Belize'],
            ['kode' => 'BEN', 'nama_negara' => 'Benin'],
            ['kode' => 'BTN', 'nama_negara' => 'Bhutan'],
            ['kode' => 'BOL', 'nama_negara' => 'Bolivia'],
            ['kode' => 'BIH', 'nama_negara' => 'Bosnia and Herzegovina'],
            ['kode' => 'BWA', 'nama_negara' => 'Botswana'],
            ['kode' => 'BRA', 'nama_negara' => 'Brazil'],
            ['kode' => 'BRN', 'nama_negara' => 'Brunei'],
            ['kode' => 'BGR', 'nama_negara' => 'Bulgaria'],
            ['kode' => 'BFA', 'nama_negara' => 'Burkina Faso'],
            ['kode' => 'BDI', 'nama_negara' => 'Burundi'],
            ['kode' => 'KHM', 'nama_negara' => 'Cambodia'],
            ['kode' => 'CMR', 'nama_negara' => 'Cameroon'],
            ['kode' => 'CAN', 'nama_negara' => 'Canada'],
            ['kode' => 'CPV', 'nama_negara' => 'Cape Verde'],
            ['kode' => 'CAF', 'nama_negara' => 'Central African Republic'],
            ['kode' => 'TCD', 'nama_negara' => 'Chad'],
            ['kode' => 'CHL', 'nama_negara' => 'Chile'],
            ['kode' => 'CHN', 'nama_negara' => 'China'],
            ['kode' => 'COL', 'nama_negara' => 'Colombia'],
            ['kode' => 'COM', 'nama_negara' => 'Comoros'],
            ['kode' => 'COG', 'nama_negara' => 'Congo'],
            ['kode' => 'COD', 'nama_negara' => 'Congo (Democratic Republic)'],
            ['kode' => 'CRI', 'nama_negara' => 'Costa Rica'],
            ['kode' => 'CIV', 'nama_negara' => 'Côte d\'Ivoire'],
            ['kode' => 'HRV', 'nama_negara' => 'Croatia'],
            ['kode' => 'CUB', 'nama_negara' => 'Cuba'],
            ['kode' => 'CYP', 'nama_negara' => 'Cyprus'],
            ['kode' => 'CZE', 'nama_negara' => 'Czech Republic'],
            ['kode' => 'DNK', 'nama_negara' => 'Denmark'],
            ['kode' => 'DJI', 'nama_negara' => 'Djibouti'],
            ['kode' => 'DMA', 'nama_negara' => 'Dominica'],
            ['kode' => 'DOM', 'nama_negara' => 'Dominican Republic'],
            ['kode' => 'ECU', 'nama_negara' => 'Ecuador'],
            ['kode' => 'EGY', 'nama_negara' => 'Egypt'],
            ['kode' => 'SLV', 'nama_negara' => 'El Salvador'],
            ['kode' => 'GNQ', 'nama_negara' => 'Equatorial Guinea'],
            ['kode' => 'ERI', 'nama_negara' => 'Eritrea'],
            ['kode' => 'EST', 'nama_negara' => 'Estonia'],
            ['kode' => 'ETH', 'nama_negara' => 'Ethiopia'],
            ['kode' => 'FJI', 'nama_negara' => 'Fiji'],
            ['kode' => 'FIN', 'nama_negara' => 'Finland'],
            ['kode' => 'FRA', 'nama_negara' => 'France'],
            ['kode' => 'GAB', 'nama_negara' => 'Gabon'],
            ['kode' => 'GMB', 'nama_negara' => 'Gambia'],
            ['kode' => 'GEO', 'nama_negara' => 'Georgia'],
            ['kode' => 'DEU', 'nama_negara' => 'Germany'],
            ['kode' => 'GHA', 'nama_negara' => 'Ghana'],
            ['kode' => 'GRC', 'nama_negara' => 'Greece'],
            ['kode' => 'GRD', 'nama_negara' => 'Grenada'],
            ['kode' => 'GTM', 'nama_negara' => 'Guatemala'],
            ['kode' => 'GIN', 'nama_negara' => 'Guinea'],
            ['kode' => 'GNB', 'nama_negara' => 'Guinea-Bissau'],
            ['kode' => 'GUY', 'nama_negara' => 'Guyana'],
            ['kode' => 'HTI', 'nama_negara' => 'Haiti'],
            ['kode' => 'HND', 'nama_negara' => 'Honduras'],
            ['kode' => 'HUN', 'nama_negara' => 'Hungary'],
            ['kode' => 'ISL', 'nama_negara' => 'Iceland'],
            ['kode' => 'IND', 'nama_negara' => 'India'],
            ['kode' => 'IRN', 'nama_negara' => 'Iran'],
            ['kode' => 'IRQ', 'nama_negara' => 'Iraq'],
            ['kode' => 'IRL', 'nama_negara' => 'Ireland'],
            ['kode' => 'ISR', 'nama_negara' => 'Israel'],
            ['kode' => 'ITA', 'nama_negara' => 'Italy'],
            ['kode' => 'JAM', 'nama_negara' => 'Jamaica'],
            ['kode' => 'JPN', 'nama_negara' => 'Japan'],
            ['kode' => 'JOR', 'nama_negara' => 'Jordan'],
            ['kode' => 'KAZ', 'nama_negara' => 'Kazakhstan'],
            ['kode' => 'KEN', 'nama_negara' => 'Kenya'],
            ['kode' => 'KIR', 'nama_negara' => 'Kiribati'],
            ['kode' => 'PRK', 'nama_negara' => 'Korea (North)'],
            ['kode' => 'KOR', 'nama_negara' => 'Korea (South)'],
            ['kode' => 'KWT', 'nama_negara' => 'Kuwait'],
            ['kode' => 'KGZ', 'nama_negara' => 'Kyrgyzstan'],
            ['kode' => 'LAO', 'nama_negara' => 'Laos'],
            ['kode' => 'LVA', 'nama_negara' => 'Latvia'],
            ['kode' => 'LBN', 'nama_negara' => 'Lebanon'],
            ['kode' => 'LSO', 'nama_negara' => 'Lesotho'],
            ['kode' => 'LBR', 'nama_negara' => 'Liberia'],
            ['kode' => 'LBY', 'nama_negara' => 'Libya'],
            ['kode' => 'LIE', 'nama_negara' => 'Liechtenstein'],
            ['kode' => 'LTU', 'nama_negara' => 'Lithuania'],
            ['kode' => 'LUX', 'nama_negara' => 'Luxembourg'],
            ['kode' => 'MKD', 'nama_negara' => 'Macedonia'],
            ['kode' => 'MDG', 'nama_negara' => 'Madagascar'],
            ['kode' => 'MWI', 'nama_negara' => 'Malawi'],
            ['kode' => 'MYS', 'nama_negara' => 'Malaysia'],
            ['kode' => 'MDV', 'nama_negara' => 'Maldives'],
            ['kode' => 'MLI', 'nama_negara' => 'Mali'],
            ['kode' => 'MLT', 'nama_negara' => 'Malta'],
            ['kode' => 'MHL', 'nama_negara' => 'Marshall Islands'],
            ['kode' => 'MRT', 'nama_negara' => 'Mauritania'],
            ['kode' => 'MUS', 'nama_negara' => 'Mauritius'],
            ['kode' => 'MEX', 'nama_negara' => 'Mexico'],
            ['kode' => 'FSM', 'nama_negara' => 'Micronesia'],
            ['kode' => 'MDA', 'nama_negara' => 'Moldova'],
            ['kode' => 'MCO', 'nama_negara' => 'Monaco'],
            ['kode' => 'MNG', 'nama_negara' => 'Mongolia'],
            ['kode' => 'MNE', 'nama_negara' => 'Montenegro'],
            ['kode' => 'MAR', 'nama_negara' => 'Morocco'],
            ['kode' => 'MOZ', 'nama_negara' => 'Mozambique'],
            ['kode' => 'MMR', 'nama_negara' => 'Myanmar'],
            ['kode' => 'NAM', 'nama_negara' => 'Namibia'],
            ['kode' => 'NRU', 'nama_negara' => 'Nauru'],
            ['kode' => 'NPL', 'nama_negara' => 'Nepal'],
            ['kode' => 'NLD', 'nama_negara' => 'Netherlands'],
            ['kode' => 'NZL', 'nama_negara' => 'New Zealand'],
            ['kode' => 'NIC', 'nama_negara' => 'Nicaragua'],
            ['kode' => 'NER', 'nama_negara' => 'Niger'],
            ['kode' => 'NGA', 'nama_negara' => 'Nigeria'],
            ['kode' => 'NOR', 'nama_negara' => 'Norway'],
            ['kode' => 'OMN', 'nama_negara' => 'Oman'],
            ['kode' => 'PAK', 'nama_negara' => 'Pakistan'],
            ['kode' => 'PLW', 'nama_negara' => 'Palau'],
            ['kode' => 'PSE', 'nama_negara' => 'Palestine'],
            ['kode' => 'PAN', 'nama_negara' => 'Panama'],
            ['kode' => 'PNG', 'nama_negara' => 'Papua New Guinea'],
            ['kode' => 'PRY', 'nama_negara' => 'Paraguay'],
            ['kode' => 'PER', 'nama_negara' => 'Peru'],
            ['kode' => 'PHL', 'nama_negara' => 'Philippines'],
            ['kode' => 'POL', 'nama_negara' => 'Poland'],
            ['kode' => 'PRT', 'nama_negara' => 'Portugal'],
            ['kode' => 'QAT', 'nama_negara' => 'Qatar'],
            ['kode' => 'ROU', 'nama_negara' => 'Romania'],
            ['kode' => 'RUS', 'nama_negara' => 'Russia'],
            ['kode' => 'RWA', 'nama_negara' => 'Rwanda'],
            ['kode' => 'KNA', 'nama_negara' => 'Saint Kitts and Nevis'],
            ['kode' => 'LCA', 'nama_negara' => 'Saint Lucia'],
            ['kode' => 'VCT', 'nama_negara' => 'Saint Vincent and the Grenadines'],
            ['kode' => 'WSM', 'nama_negara' => 'Samoa'],
            ['kode' => 'SMR', 'nama_negara' => 'San Marino'],
            ['kode' => 'STP', 'nama_negara' => 'Sao Tome and Principe'],
            ['kode' => 'SAU', 'nama_negara' => 'Saudi Arabia'],
            ['kode' => 'SEN', 'nama_negara' => 'Senegal'],
            ['kode' => 'SRB', 'nama_negara' => 'Serbia'],
            ['kode' => 'SYC', 'nama_negara' => 'Seychelles'],
            ['kode' => 'SLE', 'nama_negara' => 'Sierra Leone'],
            ['kode' => 'SGP', 'nama_negara' => 'Singapore'],
            ['kode' => 'SVK', 'nama_negara' => 'Slovakia'],
            ['kode' => 'SVN', 'nama_negara' => 'Slovenia'],
            ['kode' => 'SLB', 'nama_negara' => 'Solomon Islands'],
            ['kode' => 'SOM', 'nama_negara' => 'Somalia'],
            ['kode' => 'ZAF', 'nama_negara' => 'South Africa'],
            ['kode' => 'SSD', 'nama_negara' => 'South Sudan'],
            ['kode' => 'ESP', 'nama_negara' => 'Spain'],
            ['kode' => 'LKA', 'nama_negara' => 'Sri Lanka'],
            ['kode' => 'SDN', 'nama_negara' => 'Sudan'],
            ['kode' => 'SUR', 'nama_negara' => 'Suriname'],
            ['kode' => 'SWZ', 'nama_negara' => 'Swaziland'],
            ['kode' => 'SWE', 'nama_negara' => 'Sweden'],
            ['kode' => 'CHE', 'nama_negara' => 'Switzerland'],
            ['kode' => 'SYR', 'nama_negara' => 'Syria'],
            ['kode' => 'TWN', 'nama_negara' => 'Taiwan'],
            ['kode' => 'TJK', 'nama_negara' => 'Tajikistan'],
            ['kode' => 'TZA', 'nama_negara' => 'Tanzania'],
            ['kode' => 'THA', 'nama_negara' => 'Thailand'],
            ['kode' => 'TLS', 'nama_negara' => 'Timor-Leste'],
            ['kode' => 'TGO', 'nama_negara' => 'Togo'],
            ['kode' => 'TON', 'nama_negara' => 'Tonga'],
            ['kode' => 'TTO', 'nama_negara' => 'Trinidad and Tobago'],
            ['kode' => 'TUN', 'nama_negara' => 'Tunisia'],
            ['kode' => 'TUR', 'nama_negara' => 'Turkey'],
            ['kode' => 'TKM', 'nama_negara' => 'Turkmenistan'],
            ['kode' => 'TUV', 'nama_negara' => 'Tuvalu'],
            ['kode' => 'UGA', 'nama_negara' => 'Uganda'],
            ['kode' => 'UKR', 'nama_negara' => 'Ukraine'],
            ['kode' => 'ARE', 'nama_negara' => 'United Arab Emirates'],
            ['kode' => 'GBR', 'nama_negara' => 'United Kingdom'],
            ['kode' => 'USA', 'nama_negara' => 'United States'],
            ['kode' => 'URY', 'nama_negara' => 'Uruguay'],
            ['kode' => 'UZB', 'nama_negara' => 'Uzbekistan'],
            ['kode' => 'VUT', 'nama_negara' => 'Vanuatu'],
            ['kode' => 'VAT', 'nama_negara' => 'Vatican City'],
            ['kode' => 'VEN', 'nama_negara' => 'Venezuela'],
            ['kode' => 'VNM', 'nama_negara' => 'Vietnam'],
            ['kode' => 'YEM', 'nama_negara' => 'Yemen'],
            ['kode' => 'ZMB', 'nama_negara' => 'Zambia'],
            ['kode' => 'ZWE', 'nama_negara' => 'Zimbabwe'],
        ];

        foreach ($benderas as $bendera) {
            Bendera::create($bendera);
        }
    }
}
